# Generated by Django 5.2.5 on 2025-09-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=45)),
                ('password', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField(auto_now_add=True)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cities')),
            ],
        ),
    ]
