# Generated by Django 5.2.5 on 2025-09-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
