# Generated by Django 5.2.5 on 2025-09-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telf',
            field=models.CharField(blank=True),
        ),
    ]
