# Generated by Django 5.2.5 on 2025-09-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_genral_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telf',
        ),
    ]
