# Generated by Django 5.2.5 on 2025-09-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_genral_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
