# Generated by Django 5.2.5 on 2025-09-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_general_final_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
