# Generated by Django 5.2.6 on 2025-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_general_final_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
